name: dino_squart_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+5
  camera: ^0.10.5+2
  path: ^1.8.2
  path_provider: ^2.0.15
  percent_indicator: ^4.0.1
  progress_indicator: ^0.2.2
  fl_chart: ^0.64.0
  shared_preferences: 2.0.6
  fluttertoast: ^8.0.8
  google_mlkit_commons:
  #path: ../google_mlkit_commons
  google_mlkit_pose_detection:
    path: ../google_mlkit_pose_detection
  provider: ^6.0.1
  sqflite: ^2.0.0+3
  url_launcher: ^6.1.12
  wakelock: ^0.6.2
  flutter_plugin_android_lifecycle:
  easy_localization: ^3.0.0
  flame : ^1.10.0
  flutter_staggered_grid_view: ^0.7.0
  horizontal_picker:
    path: ../horizontal_picker-master/
  flutter_screenutil: ^5.9.0
  stroke_text: ^0.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Mabinogi_Classic_TTF.ttf
          weight: 100
        - asset: assets/fonts/Mabinogi_Classic_TTF.ttf
          weight: 200
        - asset: assets/fonts/Mabinogi_Classic_TTF.ttf
          weight: 300
        - asset: assets/fonts/Mabinogi_Classic_TTF.ttf
          weight: 400
        - asset: assets/fonts/Mabinogi_Classic_TTF.ttf
          weight: 500
        - asset: assets/fonts/Mabinogi_Classic_TTF.ttf
          weight: 600
        - asset: assets/fonts/Mabinogi_Classic_TTF.ttf
          weight: 700
        - asset: assets/fonts/Mabinogi_Classic_TTF.ttf
          weight: 800
        - asset: assets/fonts/Mabinogi_Classic_TTF.ttf
          weight: 900